# fly.toml app configuration file generated for ecom-rs on 2024-05-20T19:31:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ecom-rs"
primary_region = "waw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
