import React from 'react';
import type { Metadata } from 'next';
import Header from './ui/components/headerComponent/Header';
import Footer from './ui/components/footerComponent/Footer';

import './ui/styles/main.scss';
// import NextBreadcrumb from './ui/components/breadcrumb/breadcrumb';

export const metadata: Metadata = {
  title: 'eCommerce-Application',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {/* <NextBreadcrumb
          homeElement="Home"
          separator={<span> &gt; </span>}
          activeClasses=""
          containerClasses=""
          listClasses=""
          capitalizeLinks
        /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
