import React from 'react';
import type { Metadata } from 'next';
import Header from './ui/components/headerComponent/Header';
import Footer from './ui/components/footer/Footer';

import './ui/styles/main.scss';

export const metadata: Metadata = {
  title: 'eCommerce-Application',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
